---
# Setup installation repositories
# Standart repository for Debian / Ubuntu (https://www.rabbitmq.com/install-debian.html)
- name: import repository key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian xenial main"
    update_cache: yes
    state: present

- name: install gdebi
  apt:
    update_cache: yes
    force: yes
    pkg: gdebi
    state: present

- name: Check if esl-erlang is installed
  command: dpkg-query -W esl-erlang
  register: erlang_pkg_check
  ignore_errors: yes
  changed_when: false

#- include_tasks: install_Debian.yml
- name: "Import Erlang/OTP GPG signing key [Debian/Ubuntu]"
  apt_key:
    url: "{{ erlang_deb_gpg_url }}"
    state: present
    validate_certs: false
  register: _add_apt_key
  until: _add_apt_key is succeeded
  retries: 5
  delay: 2

- name: "Add Erlang/OTP repository [Debian/Ubuntu]"
  template:
    src: "{{ erlang_deb_repo_tpl }}"
    dest: "/etc/apt/sources.list.d/{{ erlang_deb_repo_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true

- name: "Add Erlang/OTP repository pinning preferences [Debian/Ubuntu]"
  template:
    src: "{{ erlang_deb_pinning_tpl }}"
    dest: "/etc/apt/preferences.d/{{ erlang_deb_pinning_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true

- name: "Update cache"
  apt:
    update_cache: true
  changed_when: false

- name: "Install Erlang [Debian/Ubuntu]"
  apt:
    package:
      - "erlang{{ erlang_series_deb_version | ternary ('=' + (erlang_series_deb_version | string),'') }}"
    state: present


- name: install rabbitmq-server
  apt:
    update_cache: yes
    force: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: customize logrotate rules
  template:
    src: etc/logrotate.d/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644