---
- name: install gdebi
  apt:
    update_cache: yes
    force: yes
    pkg: gdebi
    state: present

- name: Check if esl-erlang is installed
  command: dpkg-query -W esl-erlang
  register: erlang_pkg_check
  ignore_errors: yes
  changed_when: false

- include_tasks: install_Debian.yml

- name: install rabbitmq-server
  apt:
    update_cache: yes
    force: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: customize logrotate rules
  template:
    src: etc/logrotate.d/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644
